// GENERATED by `pnpm migrations:lock` from migrations.lock.json. Do not edit.
// check-migrations-immutable fails when this file and the lock disagree.
// Nested like the lock, so no line reads as `<name>: <high-entropy value>` to the secret scanner.
export const MIGRATION_CHECKSUMS: Readonly<Record<string, { sha256: string }>> = {
  'ddl.ts': {
    sha256: '49e122abc99e98a5278b838b7c53bb99c9b83bf03e0db5c38b9cafabff7b70da',
  },
  'audit/0001_audit_store.ts': {
    sha256: '270c76df980ce8167085281f12641165c0c9e9c30ed8e4e545070057e8747cce',
  },
  'audit/0002_custody_violation_fn.ts': {
    sha256: 'd372cdd6db7d640e47f7c3a6a8e98a002516930d3b0a73264c7965d9a4b2e01e',
  },
  'cp/0001_schemas_and_rls_helpers.ts': {
    sha256: '1b3b30e86b3c6d6ab229449a099460a46a63f192fa542e8f9f7a697d3361fc42',
  },
  'cp/0002_cp_identity.ts': {
    sha256: 'c73876d4065ca839ede82dacabf83d082d080370b41db7f442f320c3b16bd014',
  },
  'cp/0003_cp_sessions_and_tokens.ts': {
    sha256: 'a32c934bdcfb9ecab8ea488ac06ddb9f6173926222ccf0406c31169ea9e72085',
  },
  'cp/0004_usage_credential_governance.ts': {
    sha256: 'ae1216e77a19d8a85df813849d1739eaff31db333d37a22968918868f6fbef56',
  },
  'cp/0005_governance_epoch.ts': {
    sha256: '4c5a672a7c325cef1c4fb4151f1cdef84a12e5ddb371e0ee83dc421466c2fb58',
  },
  'cp/0006_authorization_code_sign_in.ts': {
    sha256: '79ba8a21faa716c5f14297c2b40c77feb2b32fc578c7d73cac03535f02f52b8b',
  },
  'cp/0007_app_user_graph_checked_at.ts': {
    sha256: '4db7198836f27ce60ce65a6d28aa4abf59e92dbce8c0fd4a23f65613cf2e26d0',
  },
};
