// The dev-stack .env generator (F-002 design §8.2, SEC-F002-29). Dependency-free, so it runs on
// plain Node before `pnpm install` (CI runs it before compose). It:
// - writes only [A-Za-z0-9]{48} values, so a masked value has no URL-encoded or escaped form
//   that a log could show unmasked;
// - writes mode 0600, refuses any path outside deploy/docker/dev/, and never overwrites without
//   --force; it creates the file with O_EXCL, so it never writes through a symlink;
// - with --github-mask, prints `::add-mask::<value>` for each value so the Actions log masks it.
import { randomBytes } from 'node:crypto';
import {
  chmodSync,
  closeSync,
  constants,
  existsSync,
  lstatSync,
  openSync,
  readFileSync,
  realpathSync,
  unlinkSync,
  writeSync,
} from 'node:fs';
import { basename, dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import { DEV_DIR, ENV_KEYS, type EnvKey } from './stack.ts';

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
export const VALUE_LENGTH = 48;
export const VALUE_PATTERN = /^[A-Za-z0-9]{32,}$/;

export class EnvFileError extends Error {}

/** A uniformly random [A-Za-z0-9] string (rejection sampling: no modulo bias). */
export function randomAlphanumeric(length = VALUE_LENGTH): string {
  let out = '';
  while (out.length < length) {
    for (const byte of randomBytes(length * 2)) {
      if (byte >= 248) continue; // 248 = 4 × 62
      out += ALPHABET.charAt(byte % 62);
      if (out.length === length) break;
    }
  }
  return out;
}

export interface WriteEnvOptions {
  /** Target file; relative paths resolve against `cwd`. */
  out: string;
  cwd?: string;
  force?: boolean;
  /** The folder the file must be in; defaults to deploy/docker/dev. Tests pass a temp folder. */
  allowedDir?: string;
  /** Receives `::add-mask::` lines when set (GitHub Actions). */
  mask?: (line: string) => void;
  /** Fixed values for tests; generated when absent. */
  values?: Partial<Record<EnvKey, string>>;
}

export interface WriteEnvResult {
  path: string;
  keys: EnvKey[];
}

function assertInside(allowedDir: string, target: string): void {
  const allowed = realpathSync(allowedDir);
  const parent = dirname(target);
  if (!existsSync(parent)) {
    throw new EnvFileError(`refusing ${target}: its folder does not exist`);
  }
  const realParent = realpathSync(parent);
  const rel = relative(allowed, realParent);
  if (rel === '..' || rel.startsWith(`..${sep}`) || isAbsolute(rel)) {
    throw new EnvFileError(
      `refusing ${target}: the .env generator only writes inside ${allowedDir} (SEC-F002-29)`,
    );
  }
  if (!basename(target).startsWith('.env')) {
    throw new EnvFileError(`refusing ${target}: the file name must start with .env (git-ignored)`);
  }
}

export function renderEnv(values: Record<EnvKey, string>): string {
  const lines = [
    '# Generated by `node tooling/dev-stack/src/cli.ts env`: random, local dev and CI only.',
    '# Git-ignored. Never commit it, and never reuse these values anywhere else.',
    ...ENV_KEYS.map((key) => `${key}=${values[key]}`),
  ];
  return `${lines.join('\n')}\n`;
}

export function writeEnvFile(options: WriteEnvOptions): WriteEnvResult {
  const target = resolve(options.cwd ?? process.cwd(), options.out);
  assertInside(options.allowedDir ?? DEV_DIR, target);

  let present: boolean;
  try {
    lstatSync(target); // lstat: a dangling symlink counts as present
    present = true;
  } catch {
    present = false;
  }
  if (present) {
    if (options.force !== true) {
      throw new EnvFileError(`${target} exists; pass --force to replace it`);
    }
    unlinkSync(target); // removes a symlink itself, never its target
  }

  const values = {} as Record<EnvKey, string>;
  for (const key of ENV_KEYS) {
    const value = options.values?.[key] ?? randomAlphanumeric();
    if (!VALUE_PATTERN.test(value)) {
      throw new EnvFileError(`${key} must match ${String(VALUE_PATTERN)}`);
    }
    values[key] = value;
  }

  // O_EXCL: fails if anything (including a symlink planted since the unlink) is at the path.
  const fd = openSync(target, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL, 0o600);
  try {
    writeSync(fd, renderEnv(values));
  } finally {
    closeSync(fd);
  }
  chmodSync(target, 0o600); // the umask can't widen it, but make the mode explicit
  if (options.mask !== undefined) {
    for (const key of ENV_KEYS) options.mask(`::add-mask::${values[key]}`);
  }
  return { path: target, keys: [...ENV_KEYS] };
}

/** Reads the KEY=VALUE lines of a generated .env file. */
export function readEnvFile(path: string): Partial<Record<EnvKey, string>> {
  const out: Partial<Record<EnvKey, string>> = {};
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const match = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line.trim());
    if (match === null) continue;
    const [, key, value] = match as unknown as [string, string, string];
    if ((ENV_KEYS as readonly string[]).includes(key)) out[key as EnvKey] = value;
  }
  return out;
}
