// CSS value helpers shared by the ESLint rules (this package) and @ralysa/stylelint-config, so the
// two notations of the same guard-rail can't drift apart (F-001 design §7.3; code review 4, 7).

/** Every CSS named colour (CSS Color Module Level 4), lowercase. Not `transparent`/`currentcolor`. */
export const CSS_NAMED_COLORS = [
  'aliceblue',
  'antiquewhite',
  'aqua',
  'aquamarine',
  'azure',
  'beige',
  'bisque',
  'black',
  'blanchedalmond',
  'blue',
  'blueviolet',
  'brown',
  'burlywood',
  'cadetblue',
  'chartreuse',
  'chocolate',
  'coral',
  'cornflowerblue',
  'cornsilk',
  'crimson',
  'cyan',
  'darkblue',
  'darkcyan',
  'darkgoldenrod',
  'darkgray',
  'darkgreen',
  'darkgrey',
  'darkkhaki',
  'darkmagenta',
  'darkolivegreen',
  'darkorange',
  'darkorchid',
  'darkred',
  'darksalmon',
  'darkseagreen',
  'darkslateblue',
  'darkslategray',
  'darkslategrey',
  'darkturquoise',
  'darkviolet',
  'deeppink',
  'deepskyblue',
  'dimgray',
  'dimgrey',
  'dodgerblue',
  'firebrick',
  'floralwhite',
  'forestgreen',
  'fuchsia',
  'gainsboro',
  'ghostwhite',
  'gold',
  'goldenrod',
  'gray',
  'green',
  'greenyellow',
  'grey',
  'honeydew',
  'hotpink',
  'indianred',
  'indigo',
  'ivory',
  'khaki',
  'lavender',
  'lavenderblush',
  'lawngreen',
  'lemonchiffon',
  'lightblue',
  'lightcoral',
  'lightcyan',
  'lightgoldenrodyellow',
  'lightgray',
  'lightgreen',
  'lightgrey',
  'lightpink',
  'lightsalmon',
  'lightseagreen',
  'lightskyblue',
  'lightslategray',
  'lightslategrey',
  'lightsteelblue',
  'lightyellow',
  'lime',
  'limegreen',
  'linen',
  'magenta',
  'maroon',
  'mediumaquamarine',
  'mediumblue',
  'mediumorchid',
  'mediumpurple',
  'mediumseagreen',
  'mediumslateblue',
  'mediumspringgreen',
  'mediumturquoise',
  'mediumvioletred',
  'midnightblue',
  'mintcream',
  'mistyrose',
  'moccasin',
  'navajowhite',
  'navy',
  'oldlace',
  'olive',
  'olivedrab',
  'orange',
  'orangered',
  'orchid',
  'palegoldenrod',
  'palegreen',
  'paleturquoise',
  'palevioletred',
  'papayawhip',
  'peachpuff',
  'peru',
  'pink',
  'plum',
  'powderblue',
  'purple',
  'rebeccapurple',
  'red',
  'rosybrown',
  'royalblue',
  'saddlebrown',
  'salmon',
  'sandybrown',
  'seagreen',
  'seashell',
  'sienna',
  'silver',
  'skyblue',
  'slateblue',
  'slategray',
  'slategrey',
  'snow',
  'springgreen',
  'steelblue',
  'tan',
  'teal',
  'thistle',
  'tomato',
  'turquoise',
  'violet',
  'wheat',
  'white',
  'whitesmoke',
  'yellow',
  'yellowgreen',
];

/** Alternation of the named colours, longest first so `darkred` wins over `red`. */
export const NAMED_COLOR_ALTERNATION = [...CSS_NAMED_COLORS]
  .sort((a, b) => b.length - a.length)
  .join('|');

/**
 * A named colour as a whole CSS value token (space, comma, parenthesis or `/` around it), any
 * case. `url(red.png)` and `--red-500` don't match.
 */
export const NAMED_COLOR_IN_VALUE = new RegExp(
  `(?<![\\w.\\-#/])(?:${NAMED_COLOR_ALTERNATION})(?![\\w.\\-/])`,
  'i',
);

// One CSS value token: a word, optionally followed by a (once-nested) parenthesised argument
// list, so `calc(var(--a) + 1px)` counts as one value.
const PARENS = String.raw`\((?:[^()]|\([^()]*\))*\)`;
export const CSS_VALUE_TOKEN = String.raw`(?:[^\s()/,]+(?:${PARENS})?|${PARENS})`;

/** `a b c d` where the 2nd (right) and 4th (left) values differ. */
export const ASYMMETRIC_FOUR_VALUES = new RegExp(
  String.raw`^\s*${CSS_VALUE_TOKEN}\s+(${CSS_VALUE_TOKEN})\s+${CSS_VALUE_TOKEN}\s+(?!\1\s*$)${CSS_VALUE_TOKEN}\s*$`,
);
